name: Hola Mundo

on: 
  workflow_dispatch:
 # schedule:
  #  - cron: "*/5 * * * *" # se ejectuta cada 5 min
#  push:
  #  branches:
 #     - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje Hola Mundo
        run: echo "Hola Mundo, Davide"
        
      - name: Checkout
        uses: actions/checkout@v4.4.0

      - name: Listar archivos del repo
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos"
          tree
