name: Hola Mundo

on: 
  schedule:
    - cron: "*/5 * * * *" # se ejectuta cada 5 min
  push:
    branches:
      - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje Hola Mundo
        run: echo "Hola Mundo, Davide"
